### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by calvin2021y** [maurocasas/fastindex#5]
```sh
npm run build

> build
> vite build

vite v5.4.2 building for production...
✓ 1 modules transformed.
x Build failed in 680ms
error during build:
Could not resolve "../../vendor/masmerise/livewire-toaster/resources/js" from "resources/js/app.js"
file: /opt/web/google/fastindex/resources/js/app.js
    at getRollupError (file:///opt/web/google/fastindex/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    at error (file:///opt/web/google/fastindex/node_modules/rollup/dist/es/shared/parseAst.js:388:42)
    at ModuleLoader.handleInvalidResolvedId (file:///opt/web/google/fastindex/node_modules/rollup/dist/es/shared/node-entry.js:19234:24)
    at file:///opt/web/google/fastindex/node_modules/rollup/dist/es/shared/node-entry.js:19194:26
```

nvm -v
0.40.1

 node -v
v18.20.4

**Comment by sqlraft** [comment]
after `composer.phar install -vvv`, this get fixed.

but I get new error on step: ` php artisan db:seed`

```sh
   INFO  Seeding database.  


   Illuminate\Database\QueryException 

  Database file at path [/app/fastindex/database/database.sqlite] does not exist. Ensure this is an absolute path to the database. (Connection: sqlite, SQL: insert into "users" ("name", "email", "password", "role", "updated_at", "created_at") values (User, user@user.com, $2y$12$ViQqHoTi3siCtYJNesI87OE6KkV7OMRUcn2HQaTM/DbZiQpaTXE3i, admin, 2024-10-30 12:34:07, 2024-10-30 12:34:07))

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:825
    821▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    822▕                 );
    823▕             }
    824▕ 
  ➜ 825▕             throw new QueryException(
    826▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    827▕             );
    828▕         }
    829▕     }

      +21 vendor frames 

  22  database/seeders/DatabaseSeeder.php:17
      Illuminate\Database\Eloquent\Model::__callStatic()
      +23 vendor frames 

  46  artisan:13
      Illuminate\Foundation\Application::handleCommand()


```

**Comment by sqlraft** [comment]
`php artisan migrate` fix the sqlite problem.
